export const BASE_URL = 'https://sharethoughts.onrender.com'
// export const BASE_URL = 'http://localhost:5000/'
export const USER_URL = '/api/users'
export const POST_URL = '/api/posts'
export const LIKE_URL = '/api/likes'
export const COMMENT_URL = '/api/comments'
export const CONTENT_URL = '/api/content'
export const CHAT_URL = '/api/chats'
